# Generated by Django 5.2.3 on 2025-06-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('usernme', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('cpassword', models.CharField(max_length=120)),
            ],
        ),
    ]
